package dict;

enum Phrase
{
    LOGIN_FIELD_TITLE;
    PASSWORD_FIELD_TITLE;
    REMEMBER_ME_CHECKBOX_TITLE;
    SIGN_IN_BTN;
    REGISTER_BTN;

    SEND_CHALLENGE;
    OPEN_CHALLENGE_BTN;
    ANALYSIS_BTN;
    SPECTATE_BTN;
    SETTINGS_BTN;
    LOG_OUT_BTN;

    ENTER_CALLEE;
    CHALLENGE_PARAMS_TITLE;
    CHOOSE_TIME_CONTROL;
    SEND_CHALLENGE_RESULT_SUCCESS;
    SEND_CHALLENGE_RESULT_DECLINED;
    SEND_CHALLENGE_RESULT_SAME;
    SEND_CHALLENGE_RESULT_REPEATED;
    SEND_CHALLENGE_RESULT_OFFLINE;
    SEND_CHALLENGE_RESULT_BUSY;
    SEND_CHALLENGE_RESULT_DECLINED_TITLE;
    SEND_CHALLENGE_RESULT_ERROR_TITLE;
    SEND_CHALLENGE_RESULT_SUCCESS_TITLE;

    ACCEPT_CHALLENGE;

    INCOMING_CHALLENGE_QUESTION;
    INCOMING_CHALLENGE_TITLE;

    WILL_BE_GUEST;
    JOINING_AS;
    OPEN_CHALLENGE_FIRST_TO_FOLLOW_NOTE;

    ANALYSIS_CLEAR;
    ANALYSIS_RESET;

    ENTER_SPECTATED;
    SPECTATION_ERROR_TITLE;
    SPECTATION_ERROR_REASON_OFFLINE;
    SPECTATION_ERROR_REASON_NOTINGAME;

    SETTINGS_TITLE;
    SETTINGS_MARKUP_TITLE;
    SETTINGS_MARKUP_TYPE_NONE;
    SETTINGS_MARKUP_TYPE_SIDE;
    SETTINGS_MARKUP_TYPE_OVER;
    SETTINGS_LANGUAGE_TITLE;

    CHATBOX_MESSAGE_PLACEHOLDER;
    SPECTATOR_JOINED_MESSAGE;
    SPECTATOR_LEFT_MESSAGE;
    DRAW_OFFERED_MESSAGE;
    DRAW_CANCELLED_MESSAGE;
    DRAW_ACCEPTED_MESSAGE;
    DRAW_DECLINED_MESSAGE;
    TAKEBACK_OFFERED_MESSAGE;
    TAKEBACK_CANCELLED_MESSAGE;
    TAKEBACK_ACCEPTED_MESSAGE;
    TAKEBACK_DECLINED_MESSAGE;

    RESOLUTION_NONE;
    RESOLUTION_MATE;
    RESOLUTION_BREAKTHROUGH;
    RESOLUTION_RESIGN;
    RESOLUTION_DISCONNECT;
    RESOLUTION_AGREEMENT;
    RESOLUTION_REPETITON;
    RESOLUTION_HUNDRED;
    RESOLUTION_WINNER_POSTFIX;

    OPENING_STARTING_POSITION;

    PROMOTION_DIALOG_TITLE;
    PROMOTION_DIALOG_QUESTION;

    CHAMELEON_DIALOG_TITLE;
    CHAMELEON_DIALOG_QUESTION;

    RESIGN_BTN_TEXT;
    RESIGN_CONFIRMATION_MESSAGE;
    OFFER_DRAW_BTN_TEXT;
    TAKEBACK_BTN_TEXT;
    CANCEL_DRAW_BTN_TEXT;
    CANCEL_TAKEBACK_BTN_TEXT;
    DRAW_QUESTION_TEXT;
    TAKEBACK_QUESTION_TEXT;

    WIN_MESSAGE_PREAMBLE;
    LOSS_MESSAGE_PREAMBLE;
    GAME_OVER_REASON_MATE;
    GAME_OVER_REASON_BREAKTHROUGH;
    GAME_OVER_REASON_TIMEOUT;
    GAME_OVER_REASON_RESIGN;
    GAME_OVER_REASON_DISCONNECT;
    GAME_OVER_REASON_THREEFOLD;
    GAME_OVER_REASON_HUNDRED;
    GAME_OVER_REASON_AGREEMENT;
    GAME_OVER;
    GAME_ENDED;

    ALREADY_LOGGED;
    INVALID_PASSWORD;
    ALREADY_REGISTERED;
    SPECIFY_BOTH_REG_ERROR;

    CONNECTION_LOST_ERROR;
    CONNECTION_ERROR_OCCURED;

    CONFIRM;
    CANCEL;
    RETURN;
}