package dict;

enum Phrase
{
    LANGUAGE_NAME;

    SEND_CHALLENGE;
    OPEN_CHALLENGE_BTN;
    ANALYSIS_BTN;
    SPECTATE_BTN;
    PROFILE_BTN;
    SETTINGS_BTN;
    LOG_OUT_BTN;

    PLAYER_NOT_FOUND;

    ENTER_CALLEE;
    CHALLENGE_PARAMS_TITLE;
    CHOOSE_TIME_CONTROL;
    CHOOSE_COLOR;
    COLOR_RANDOM;
    SEND_CHALLENGE_RESULT_SUCCESS;
    SEND_CHALLENGE_RESULT_DECLINED;
    SEND_CHALLENGE_RESULT_SAME;
    SEND_CHALLENGE_RESULT_REPEATED;
    SEND_CHALLENGE_RESULT_OFFLINE;
    SEND_CHALLENGE_RESULT_BUSY;
    SEND_CHALLENGE_RESULT_NOTFOUND;
    SEND_CHALLENGE_RESULT_DECLINED_TITLE;
    SEND_CHALLENGE_RESULT_ERROR_TITLE;
    SEND_CHALLENGE_RESULT_SUCCESS_TITLE;

    INCOMING_CHALLENGE_TITLE;
    INCOMING_CHALLENGE_TEXT;
    ACCEPT_CHALLENGE;
    ACCEPT_CHALLENGE_RESULT_CANCELLED;
    ACCEPT_CHALLENGE_RESULT_OFFLINE;
    ACCEPT_CHALLENGE_RESULT_BUSY;

    COPY_BTN_TOOLTIP;
    COPY_BTN_SUCCESS_TOOLTIP;

    //Analysis screen

    ANALYSIS_OVERVIEW_TAB_NAME;
    ANALYSIS_SET_POSITION_BTN_TOOLTIP;
    ANALYSIS_SHARE_BTN_TOOLTIP;
    
    ANALYSIS_BRANCHING_TAB_NAME;
    ANALYSIS_BRANCHING_HELP_LINK_TEXT;
    ANALYSIS_BRANCHING_HELP_DIALOG_TITLE;
    ANALYSIS_BRANCHING_HELP_DIALOG_TEXT;

    ANALYSIS_OPENINGS_TAB_NAME;
    ANALYSIS_OPENINGS_TEASER_TEXT;

    ANALYSIS_CLEAR_BTN_TOOLTIP;
    ANALYSIS_RESET_BTN_TOOLTIP;
    ANALYSIS_TO_STARTPOS_BTN_TOOLTIP;
    ANALYSIS_FLIP_BOARD_BTN_TOOLTIP;
    ANALYSIS_IMPORT_BTN_TOOLTIP;
    ANALYSIS_WHITE_TO_MOVE_OPTION_TEXT;
    ANALYSIS_BLACK_TO_MOVE_OPTION_TEXT;
    ANALYSIS_APPLY_CHANGES_BTN_TEXT;
    ANALYSIS_DISCARD_CHANGES_BTN_TEXT;

    ANALYSIS_INPUT_SIP_PROMPT_TEXT;
    ANALYSIS_INVALID_SIP_WARNING_TITLE;
    ANALYSIS_INVALID_SIP_WARNING_TEXT;

    //Share dialog

    SHARE_DIALOG_TITLE;

    SHARE_POSITION_TAB_NAME;
    SHARE_SIP_HEADER;
    SHARE_IMAGE_HEADER;
    SHARE_DOWNLOAD_PNG_BTN_TEXT;
    SHARE_DOWNLOAD_PNG_MARKUP_CHECKBOX_TEXT;
    SHARE_DOWNLOAD_PNG_DIMENSIONS_LABEL_TEXT;
    SHARE_DOWNLOAD_PNG_KEEP_RATIO_CHECKBOX_TEXT;
    SHARE_DOWNLOAD_PNG_BGCOLOR_LABEL_TEXT;
    SHARE_DOWNLOAD_PNG_TRANSPARENT_BG_CHECKBOX_TEXT;

    SHARE_GAME_TAB_NAME;
    SHARE_LINK_HEADER;
    SHARE_PIN_HEADER;
    SHARE_ANIMATED_GIF_HEADER;
    SHARE_DOWNLOAD_GIF_WIDTH_LABEL_TEXT;
    SHARE_DOWNLOAD_GIF_INTERVAL_LABEL_TEXT;
    SHARE_EXPORT_AND_DOWNLOAD_BTN_TEXT;

    SHARE_EXPORT_TAB_NAME;
    SHARE_EXPORT_AS_STUDY_HEADER;
    SHARE_NAME_PREFIX_LABEL;
    SHARE_STUDY_NAME_TEXTFIELD_PLACEHOLDER;
    SHARE_EXPORT_NEW_BTN_TEXT;
    SHARE_OVERWRITE_BTN_TEXT_TEMPLATE;
    SHARE_EXPORT_AS_QUESTION_MARKS_TEASER;
    SHARE_COMING_SOON;

    //Open challenge joining

    OPENJOIN_CHALLENGE_BY_HEADER;
    OPENJOIN_COLOR_WHITE_OWNER;
    OPENJOIN_COLOR_BLACK_OWNER;
    OPENJOIN_COLOR_RANDOM;
    OPENJOIN_RATED;
    OPENJOIN_UNRATED;
    OPENJOIN_ACCEPT_BTN_TEXT;

    //Main menu dialogs

    CHANGELOG_DIALOG_TITLE;

    LOGIN_DIALOG_TITLE;
    LOGIN_LOG_IN_MODE_TITLE;
    LOGIN_REGISTER_MODE_TITLE;
    LOGIN_LOGIN_FIELD_NAME;
    LOGIN_PASSWORD_FIELD_NAME;
    LOGIN_REPEAT_PASSWORD_FIELD_NAME;
    LOGIN_REMEMBER_ME;
    LOGIN_REMAIN_LOGGED;
    LOGIN_LOG_IN_BTN_TEXT;
    LOGIN_REGISTER_BTN_TEXT;
    
    LOGIN_WARNING_MESSAGEBOX_TITLE;
    LOGIN_INVALID_PASSWORD_WARNING_TEXT;
    LOGIN_PASSWORDS_DO_NOT_MATCH;
    LOGIN_ALREADY_REGISTERED_WARNING_TEXT;
    LOGIN_LOGIN_NOT_SPECIFIED_WARNING_TEXT;
    LOGIN_PASSWORD_NOT_SPECIFIED_WARNING_TEXT;
    LOGIN_REPEATED_PASSWORD_NOT_SPECIFIED_WARNING_TEXT;
    LOGIN_BAD_LOGIN_LENGTH_WARNING_TEXT;
    LOGIN_BAD_PASSWORD_LENGTH_WARNING_TEXT;

    SETTINGS_DIALOG_TITLE;
    SETTINGS_GENERAL_TAB_TITLE;
    SETTINGS_APPEARANCE_TAB_TITLE;
    SETTINGS_CONTROLS_TAB_TITLE;
    SETTINGS_INTEGRATIONS_TAB_TITLE;

    SETTINGS_LANGUAGE_OPTION_NAME;
    SETTINGS_MARKUP_OPTION_NAME;
    SETTINGS_PREMOVES_OPTION_NAME;
    SETTINGS_BRANCHING_TYPE_OPTION_NAME;
    SETTINGS_BRANCHING_SHOW_TURN_COLOR_OPTION_NAME;
    SETTINGS_SILENT_CHALLENGES_OPTION_NAME;

    SETTINGS_MARKUP_ALL_OPTION_VALUE;
    SETTINGS_MARKUP_LETTERS_OPTION_VALUE;
    SETTINGS_MARKUP_NONE_OPTION_VALUE;

    SETTINGS_BRANCHING_TYPE_TREE_OPTION_VALUE;
    SETTINGS_BRANCHING_TYPE_OUTLINE_OPTION_VALUE;
    SETTINGS_BRANCHING_TYPE_PLAIN_OPTION_VALUE;

    SETTINGS_DISABLED_OPTION_VALUE;
    SETTINGS_ENABLED_OPTION_VALUE;


    ENTER_SPECTATED;
    SPECTATION_ERROR_TITLE;
    SPECTATION_ERROR_REASON_OFFLINE;
    SPECTATION_ERROR_REASON_NOTINGAME;


    ENTER_PROFILE_OWNER;
    GAMES;
    STUDIES;


    CHATBOX_MESSAGE_PLACEHOLDER;
    SPECTATOR_JOINED_MESSAGE;
    SPECTATOR_LEFT_MESSAGE;
    OPPONENT_DISCONNECTED_MESSAGE;
    OPPONENT_RECONNECTED_MESSAGE;
    DRAW_OFFERED_MESSAGE;
    DRAW_CANCELLED_MESSAGE;
    DRAW_ACCEPTED_MESSAGE;
    DRAW_DECLINED_MESSAGE;
    TAKEBACK_OFFERED_MESSAGE;
    TAKEBACK_CANCELLED_MESSAGE;
    TAKEBACK_ACCEPTED_MESSAGE;
    TAKEBACK_DECLINED_MESSAGE;

    RESOLUTION_NONE;
    RESOLUTION_MATE;
    RESOLUTION_BREAKTHROUGH;
    RESOLUTION_RESIGN;
    RESOLUTION_ABORT;
    RESOLUTION_DISCONNECT;
    RESOLUTION_AGREEMENT;
    RESOLUTION_REPETITON;
    RESOLUTION_HUNDRED;
    RESOLUTION_TIMEOUT;
    RESOLUTION_WINNER_POSTFIX;

    OPENING_STARTING_POSITION;

    PROMOTION_DIALOG_TITLE;
    PROMOTION_DIALOG_QUESTION;

    CHAMELEON_DIALOG_TITLE;
    CHAMELEON_DIALOG_QUESTION;

    CHANGE_ORIENTATION_BTN_TOOLTIP;
    RESIGN_BTN_TOOLTIP;
    RESIGN_BTN_ABORT_TOOLTIP;
    RESIGN_CONFIRMATION_MESSAGE;
    ABORT_CONFIRMATION_MESSAGE;
    OFFER_DRAW_BTN_TOOLTIP;
    TAKEBACK_BTN_TOOLTIP;
    CANCEL_DRAW_BTN_TOOLTIP;
    CANCEL_TAKEBACK_BTN_TOOLTIP;
    DRAW_QUESTION_TEXT;
    TAKEBACK_QUESTION_TEXT;
    EXPLORE_IN_ANALYSIS_BTN_TOOLTIP;
    REMATCH_BTN_TOOLTIP;
    ADD_TIME_BTN_TOOLTIP;
    LIVE_SHARE_BTN_TOOLTIP;

    WIN_MESSAGE_PREAMBLE;
    LOSS_MESSAGE_PREAMBLE;
    GAME_OVER_REASON_MATE;
    GAME_OVER_REASON_BREAKTHROUGH;
    GAME_OVER_REASON_TIMEOUT;
    GAME_OVER_REASON_RESIGN;
    GAME_OVER_REASON_DISCONNECT;
    GAME_OVER_REASON_THREEFOLD;
    GAME_OVER_REASON_HUNDRED;
    GAME_OVER_REASON_AGREEMENT;
    GAME_OVER_REASON_ABORT;
    GAME_OVER;
    GAME_ENDED;

    GAME_OVER_MESSAGE_SUFFIX_WIN;
    GAME_OVER_MESSAGE_SUFFIX_TIMEOUT;
    GAME_OVER_MESSAGE_SUFFIX_RESIGN;
    GAME_OVER_MESSAGE_SUFFIX_DISCONNECT;
    GAME_OVER_MESSAGE_DRAW;
    GAME_OVER_MESSAGE_ABORT;

    //Connection management

    CONNECTION_LOST_ERROR;
    CONNECTION_ERROR_OCCURED;
    SESSION_CLOSED_ALERT_TITLE;
    SESSION_CLOSED_ALERT_TEXT;
    RECONNECTION_POP_UP_TEXT;
    RECONNECTION_POP_UP_TITLE;

    //Copy

    CLIPBOARD_ERROR_ALERT_TITLE;
    CLIPBOARD_ERROR_ALERT_TEXT;

    //Special

    CORRESPONDENCE_TIME_CONTROL_NAME;
}